title: 四叶技术播客
description: |
  4ye.fm 为编程爱好者，以及对计算机与编程有兴趣的朋友提供精心准备的播客节目。力求通俗易懂，让大家都有所收获。
url: "http://192.168.1.39:4000"
# Build settings
markdown: kramdown

collections: 
  broadcasts:
    output: true